### ISSUE TITLE
dreamcat4 - general commentary

### ISSUE THREAD

**Issue by felixfung** [dreamcat4/skippy-xd#132] opened 2023-06-19 07:46 UTC
@dreamcat4 I am creating this issue to keep track of our discussions in #129 #131.

**Comment by dreamcat4** [comment] 2023-06-19 12:08
Thanks felix. I have just reverted selectively those 2 commit now. Hopefully it does not affect your other work on master branch. And was a clean changesets.

I am still not ready to have the time window open for those scheduled testing. But the same 2-weeks time window still applied. That I am hoping not to delay those catch-up for too long.

The commit is kept back in git history. It may be decided later on (after a proper verification of testing). Whether or not to re-apply those 2 removal commit. Hope this is reasonable oversight for those specific changes.

Other alt-tab changes will also be evaluated during same process. During those catchup. Along with finding out a bit more about new pager features, since so many other significant changes.

Hope this clarifies for today now. Until [for myself], to come back later on. Many thanks.

**Comment by felixfung** [comment] 2023-07-04 14:33
Thanks for the feedback....

> paging remains broken (on my KDE / ultrawide / multimonitor combo). I have no interest and do not support this feature because... its always broken!

I am quite surprised. How is it broken?

> boxy layout remains in same broken state (for me) as ever - it's still another feature, which i do not use

By chance I merged #149 which to me greatly improved boxy layout 12 hours ago, it *might* improve things for you?

> If these features works fine on your setups and DEs: then that's great. Just so sorry but i cannot participate while they remain [that much broken]. It's just not worth my time.

Yes everything works fine for me, I thought I fixed all bugs other than #125. I'm surprised to learn about bugs and regressions on KDE. Thanks for reporting.

> You tool away the sort-by-columns setting.

Yes nice pointing it out. I will update that when `exposeLayout = xd`, it will be sorting by row, z-order to be precise.

> when i open skippy in a terminal, then press "Esc" key to cancel exit / dismiss. Skippy no longer focuses back to the original active window (which was the terminal app). Skippy used to works just fine those ways. So i regard that as a regression bug to be fixed. Or otherwise perhaps a mis-configuration on my part if it works? Needs further investigating

Again a bit surprised...

Yes I made changes on this area in #118. The code logic is quite obvious here:

https://github.com/dreamcat4/skippy-xd/blob/1a4cf05107f3b75094d470abacf2b8486ff30f9a/src/skippy.c#L513
https://github.com/dreamcat4/skippy-xd/blob/1a4cf05107f3b75094d470abacf2b8486ff30f9a/src/clientwin.c#L694
https://github.com/dreamcat4/skippy-xd/blob/1a4cf05107f3b75094d470abacf2b8486ff30f9a/src/skippy.c#L888

And it works perfectly on my system....

> I have superficially tried some of the basic features in new code. And found about 2/3rd's is broken

Can you please describe how it is broken?

**Comment by dreamcat4** [comment] 2023-07-05 00:42
### Update

>     * paging remains broken (on my KDE / ultrawide / multimonitor combo)
>     * boxy layout remains in broken state (for me)

Will try to make the video about those tomorrow now, for you to see those breakage(s). As today's time got (mis)used for these other changes:

#### Focus back to original window on cancel

>     * when i open skippy in a terminal, then press "Esc" key to cancel exit / dismiss. Skippy no longer focuses back to the original active window

* Fixed by 65b8e854c32d168e410c12fa5a1ae9c2b871b862

#### Reversing keys direction

>     * reversKeysDirection

* Fixed by 3b84bdb62867a76e69638cde1c2d69656169ea17

#### Runner script

>     * fixing the runner script

* Mostly fixed by ae6de07a670e97ad5c13b5b8a21477e1c49c8ca0

#### Config file parsing (regexps)

> config file parsing to make a bit nicer experience:
> 
>     * Support `setting = val # comment at the end of a line`
>     * Support `; semicolon` comments for general INI format spec (already works, just gives a warning msg)

+ Plus
* Support `;comments` and `//comments`

* Fixed by 132399f1e11d603f5706ac510c75ce4c8d0daac6

**Comment by dreamcat4** [comment] 2023-07-05 00:43
> Can you please describe how it is broken?

This will come as video tomorrow (or day after tomorrow).

**Comment by felixfung** [comment] 2023-07-10 04:43
@dreamcat4 I have done a crazy thing: installed a bunch of environments including GNOME and KDE, and tested skippy on all of them, and summarized them here: https://github.com/dreamcat4/skippy-xd/wiki/Adoption#compatible-desktop-environmentswindow-managers. They all work!

For your environment, KDE, ultrawide / multimonitor, it is known issues that multiple monitor and lazy transparency causes problems #153 #126 . While testing these environments, I found a weird behaviour where all visuals are broken, but it seems restarting skippy would solve this bug. I have used skippy thousands of times and this never happened, so presumably it is a weird edge case bug that I don't know how to reproduce.

Would love to know what bugs you are experiencing?

**Comment by dreamcat4** [comment] 2023-07-10 10:08
> Would love to know what bugs you are experiencing?

dont worry @felixfung will be delivering that video as promised very soon.  indeed most likely not related to the de, certain other type of multi monitor issue.

also must really apologize for taking so long over providing this. however it has enabled the extra time necessary to be much more thorough. to document more fully and more clearly all the things.

you should also be aware:

it is not clear to me whether or not you actually have a setup over there to reproduce locally. although maybe you can? it may be possible with a minimum of 2 monitors total. connected. is the expected minimum requirement.

one final point:

video has very high total resolution. so best to view on a 4k monitor. (since its combined 3 monitors). but maybe not essential. if you don't have that. then can still pause it to take still's screencaps of frames. to zoom/pan some screencaps... but everything in the video will also be (is already now) fully documented in markdown.

won't be too much longer (this time the promise is easier to meet, since mostly donw). again my apologies because this deliverable was promised much earlier. however now due pretty soon.

closing this issue.... b/c to open next for a clean issue. either today / tomorrow.

**Closed by dreamcat4** 2023-07-10 10:08 UTC
Labels: question, refactor
