### ISSUE TITLE
Feature request and some ideas

### ISSUE THREAD

**Issue by revast** [dreamcat4/skippy-xd#3] opened 2018-11-29 14:59 UTC
- Number one feature, obviously (at least for me, but also seen elsewhere) would be that iconified ("minimized") windows also have a x11 miniature graphics.

- Then, there is a bountysource open here, and skippy is mentioned in the discussion.
https://www.bountysource.com/issues/3327306-expose-like-task-switcher-for-xfce

- I will try to spread the good news further, on places like reddit, the wikipedia entry, ubuntu, arch wiki etc..
It would be also great to make a small website for it, here on github (but lets wait for richardgv first). Searching "expose linux" gives skippy-xd as first hit btw.

- I also can help with debian packaging, and can request adding skippy-xd to Debian, making an Ubuntu ppa...

my motivation is that I am using skippy-xd on my selfmade linux distribution in the default install.

**Comment by dreamcat4** [comment] 2018-11-29 16:19
Ah! Perhaps you can clarify something for me then:

Because I am not sure why people are saying that skippy does not show previews of minimized windows... because in my own desktop environment (budgie-wm). If I click minimize then the window is still showing up fully in the previews. As-if it were not minimized.

Isn't that the expected / desired behaviour? What am I missing here? Bearing in mind that I really don't want to be switching to another DE to trythis out myself, I was just wondering what other people in other DEs were seeing. Or am I misunderstanding the meaning of that specifc bug?

**Comment by revast** [comment] 2018-11-30 01:47
Yes, that would be the EXACTLY the desired thing we want to have, essentially the same way for example also OSX does it. (BUT on OSX, when you park windows in the Dock, they also are omitted from being shown...on a side note, I actually like that particular behaviour, haven't seen it replicated (yet) properly on the linux side, kdocker is great for minimizing to tray though..)

Ok consider this two application-windows in XFCE (XFWM4):
http://imgur.com/kmFzVRGl.png
now when I minimize one of the windows: 
http://imgur.com/YCJcJe8l.png

With Compiz (yes I know its old!) the minimized windows are totally hidden, not even the frame is shown. I have seen a workaround with a python script which un-minimizes ("un-iconifies") the windows for the time the miniature previews are displayed, and minimizes them again afterwards, but this comes with quite an overhead. For details, see [here](https://unix.stackexchange.com/questions/324853/a-quickway-to-unminimize-all-minimized-via-bash-prompt-or-some-installable-utili). That code could enventually also be used as a base for a workaround to allow skippy-xd display it's miniatures properly without gonig too deep in the X11 domain.

I really do not know what's going on there, but this looks like the two are related..
I will ask on XFCE developers IRC channel and file a bug at XFCE if it's on their side..


But there is the exact same behaviour with Openbox, btw:
http://i.imgur.com/ZkmZp85.png
http://i.imgur.com/vtMGDj6.png

I'll try with budgie Window Manager as well... (which PPA is best to try with?)




Speaking of compiz, I think that this:
http://imgur.com/pFddOjGl.png
is much more readable than

this from skippy-xd.
http://imgur.com/wMTTUiDl.png 
So far I could not replicate that, for example I cannot get all titles shown on all windows, and the different sizes of the windows are also not so great.. 
shall I file a bug ticket here for that?

As you can see on the last two pictures, I have most of the time way too much open to use skippy efficiently. The compiz scale plugin is a bit better, but secretly I was thinking of a grouping option, which can sort windows by their kind... ;-)

**Comment by revast** [comment] 2018-11-30 10:31
yours from git master. skippy-xd v0.5.2~pre (2018.09.09) - "Puzzlebox" Edition

I already have built a debian package for [Ubuntu 18.04](http://openartisthq.org/debian/bionic64/skippy-xd_0.5.2~pre-ubuntu18.04.1_amd64.deb)

**Comment by dreamcat4** [comment] 2018-11-30 11:08
Thank you for this, and making a debian package is also most welcome.

As for the black screen whilst minimuzing... this seems to be (as far as I can tell) an issue caused by specific compositors. So unfortunately because of that I really cannot see a fix would be within my capabilities here. However if someone wants to submit any PRs for stuff like this. Then I'm very please to include / merge them for a single unified release.

Crazy stuff like temporarily un-minimizing windows would need to be under configuration though (to be switched on/off, depending on specific users). Mostly for performance reason(s).

Another way to solve the problem is to remember the last un-minimized version of the window, save that to a temporary folder on the disk. Or keep in-memory. That would actually be a much better way to do it. And much preffered solution. - I'm still not going to be doing it though. As I have other issues that are higher priority, I need to work on those ones instead.

It's also possible to selectively combine both approaches, to un-minimuze those few remaining windows which were started minimized (never before drawn). Whilst that is pretty excessive amount of work to achieve that result, I am not actually against merging that from soneobe else's PR.

My overall opinion is: it's probably easier to get around the problem by switching to use a different compositor / window manager. Like I said earlier : I use ubuntu budgie here, and it seems to be based on mutter compositor. It does not have this problem !

**Comment by revast** [comment] 2018-11-30 11:48
I am gonna try kwin_x11 now as well, but mutter is more than a compositor/window-mangager. It's fact that partly because of that budgie gets rewritten from scratch right now.

**Comment by revast** [comment] 2018-11-30 13:35
ok, same result with kwin
http://i.imgur.com/lZLJubP.png

actually kwin has expos'e builtin, and this works properly:
http://i.imgur.com/rTkMOtj.png

but kwin eats my processor time for breakfast (at least when I am in a VM and without tweaking it further..)

**Comment by dreamcat4** [comment] 2018-11-30 18:58
You know, for fvwm, it appears there are some version(s) that will work with the 'compton' compositor. I was briefly introduced to that compositor whilst trying MATE desktop environemnt.

The only reason I bring it up is because comptom seems both fast and efficient. And has many possible options under configuration. So if you are lucky, it might be a supportive project for these minimized windows previews. Not that i have actually checked its in there myself. But even if it isn't, it would nevertheless still be the specific compositor i would recommend for submitting such patches to. (for the fvwm people, at least).

The other MATE compositor was called marcos? i think? Not really sure about that one but maybe it already had window previews working anyhow. Just thought I'd mention that since you seem to be trying all these ones out at the moment.

**Comment by revast** [comment] 2018-11-30 20:07
Yeah I know compton, I have it installed by default on my distribution (albeit not activated by default). I tried marco , no also does not work with minimized windows.

**Comment by revast** [comment] 2018-12-02 14:01
One thing I also find cool at using kwin_x11: the ability to type in the expos'e interface. This lessens the  windows to the ones where the title is in the name I typed - very helpful feature

**Comment by dreamcat4** [comment] 2019-03-14 08:26
Just a quick note: Thankfully I now have noticed the minimize bug. Which appears [some times] but not others. So there might be some kind of potential for me to at least try to work on that now. Whilst still bearing in mind that Richard was very skeptical about being able to ever fix this (at least properly, to the same level or quality as other visible windows). Due to the way xwindows works / does not work.

Also in terms of 'special windows'. There was also an other issue discovered, with other types of special window. For example activation whilst a WINE program was the active window --> causes segfault.

**Comment by felixfung** [comment] 2023-03-06 23:38
Fixed in #41

**Closed** 2023-03-06 23:42 UTC
Labels: enhancement
